// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjoRDn7mtfZn39Vu4Mpp6e9ytoJghbAOE',
    appId: '1:883673425825:web:d6848bc8bcb2eca9324de0',
    messagingSenderId: '883673425825',
    projectId: 'dam-u4-proyecto-cd91b',
    authDomain: 'dam-u4-proyecto-cd91b.firebaseapp.com',
    storageBucket: 'dam-u4-proyecto-cd91b.appspot.com',
    measurementId: 'G-EF0ZC46ZQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8WbSBYxoKNiXpa8pyd8zz9-vlWqg1uWY',
    appId: '1:883673425825:android:f62e2a2eaf0b848a324de0',
    messagingSenderId: '883673425825',
    projectId: 'dam-u4-proyecto-cd91b',
    storageBucket: 'dam-u4-proyecto-cd91b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKiJ1LiTrJ8hoSSTV6myRKTTwUu11xhDI',
    appId: '1:883673425825:ios:077b1c791a02d071324de0',
    messagingSenderId: '883673425825',
    projectId: 'dam-u4-proyecto-cd91b',
    storageBucket: 'dam-u4-proyecto-cd91b.appspot.com',
    iosBundleId: 'mx.edu.ittepic.damU4P1',
  );
}
